### ISSUE TITLE
Is there a recommended way to vendor dependencies with bootboot?

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [Shopify/bootboot#29]
I'm trying out bootboot for our next rails upgrade, and from what I can tell bundler is only vendoring one set of dependencies. My goal was to have both sets of dependencies available and managed by bootboot so that our CI and deployments could be toggled with `DEPENDENCIES_NEXT` and use vendored dependencies for either version.

Am I missing something and this is possible with bootboot? I'm curious if anyone is using bootboot and also vendoring gems.

I tested this out by cloning https://github.com/testdouble/bootboot-example and running
```
$ bundle install
$ bundle bootboot
$ RAILS_NEXT=1 bundle install
$ bundle pack
$ RAILS_NEXT=1 bundle pack
```

Thanks!

**Comment by Edouard-chin** [comment]
We never had the use case to vendor dependencies , so I didn't implement this feature. I think it could be a good addition to the plugin so if anyone wants to tackle that 🥇

**Comment by MarkyMarkMcDonald** [comment]
Makes sense, thanks for the info! I think we're going to keep our current strategy of having multiple Gemfiles (we already have some tooling setup for this), but I might look into adding support for vendoring to bootboot in the future.
