### ISSUE TITLE
Ruby version issues

### ISSUE THREAD

**Issue by maths22** [Shopify/bootboot#50]
We have the following in our `Gemfile`: 
```
ruby ">= 2.7.0", "< 3.1"
```

When running with bootboot on ruby 2.7.6, we get the following error:
```
Could not find gem 'Ruby (= 2.7.6)' in Bootboot plugin Ruby source.

The source contains the following gems matching 'Ruby':
  * Ruby-2.7.0
```

**Comment by adamstegman** [comment]
@maths22 did #55 solve your issue? I ask because a couple folks on our team are still running into this error, even on v0.2.2.
